# -*- coding: utf-8 -*-
"""DSAURFA Project STSR Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_z7lpz4Qv5JOnV0lHV_28Pcb9h1aJ_W
"""

!pip install scipy

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("inline")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy.stats import skewnorm
import warnings; warnings.filterwarnings("ignore")

RNG = np.random.default_rng(2024)

# Class Definitions
CLASSES = [
    # REAL
    {
        "label": "Real_FF",        "dataset_src": "ff++",     "is_fake": False,
        "fft_mean":    (0.41, 0.04), "fft_std":  (0.18, 0.02),
        "fft_skew":    (0.12, 0.08), "fft_kurt": (2.85, 0.30),
        "dct_low":     (0.72, 0.05), "dct_mid":  (0.19, 0.04), "dct_high": (0.09, 0.02),
        "hpf_mean":    (0.02, 0.01), "hpf_std":  (0.08, 0.01), "hpf_kurt": (3.10, 0.25),
        "azimuth":     (0.05, 0.02), "rad_peak": (0.07, 0.01),
        "grid_32":     (0.01, 0.005),"grid_16":  (0.01, 0.004),
        "jpeg_ghost":  (0.12, 0.04), "ela_mean": (0.05, 0.02), "ela_std":  (0.03, 0.01),
        "snr":         (32.0, 2.5),  "chroma":   (0.04, 0.01),
    },
    {
        "label": "Real_DFDC",      "dataset_src": "dfdc",     "is_fake": False,
        "fft_mean":    (0.43, 0.05), "fft_std":  (0.17, 0.03),
        "fft_skew":    (0.10, 0.07), "fft_kurt": (2.90, 0.28),
        "dct_low":     (0.70, 0.06), "dct_mid":  (0.21, 0.05), "dct_high": (0.09, 0.02),
        "hpf_mean":    (0.02, 0.01), "hpf_std":  (0.07, 0.01), "hpf_kurt": (3.05, 0.22),
        "azimuth":     (0.04, 0.02), "rad_peak": (0.08, 0.01),
        "grid_32":     (0.01, 0.004),"grid_16":  (0.01, 0.003),
        "jpeg_ghost":  (0.14, 0.05), "ela_mean": (0.06, 0.02), "ela_std":  (0.04, 0.01),
        "snr":         (31.5, 2.8),  "chroma":   (0.05, 0.01),
    },
    # DEEPFAKES (FF++)
    {
        "label": "DeepFakes",      "dataset_src": "ff++",     "is_fake": True,
        "fft_mean":    (0.48, 0.06), "fft_std":  (0.22, 0.03),
        "fft_skew":    (0.28, 0.10), "fft_kurt": (3.45, 0.35),
        "dct_low":     (0.58, 0.06), "dct_mid":  (0.27, 0.05), "dct_high": (0.15, 0.03),
        "hpf_mean":    (0.07, 0.02), "hpf_std":  (0.14, 0.02), "hpf_kurt": (4.20, 0.40),
        "azimuth":     (0.18, 0.04), "rad_peak": (0.14, 0.02),
        "grid_32":     (0.09, 0.02), "grid_16":  (0.04, 0.01),
        "jpeg_ghost":  (0.32, 0.07), "ela_mean": (0.16, 0.04), "ela_std":  (0.09, 0.02),
        "snr":         (26.4, 3.1),  "chroma":   (0.14, 0.03),
    },
    {
        "label": "Face2Face",      "dataset_src": "ff++",     "is_fake": True,
        "fft_mean":    (0.46, 0.05), "fft_std":  (0.20, 0.03),
        "fft_skew":    (0.22, 0.09), "fft_kurt": (3.20, 0.30),
        "dct_low":     (0.61, 0.06), "dct_mid":  (0.25, 0.05), "dct_high": (0.14, 0.03),
        "hpf_mean":    (0.05, 0.02), "hpf_std":  (0.11, 0.02), "hpf_kurt": (3.80, 0.35),
        "azimuth":     (0.12, 0.03), "rad_peak": (0.11, 0.02),
        "grid_32":     (0.05, 0.01), "grid_16":  (0.08, 0.02),
        "jpeg_ghost":  (0.26, 0.06), "ela_mean": (0.13, 0.03), "ela_std":  (0.07, 0.02),
        "snr":         (27.8, 2.9),  "chroma":   (0.11, 0.02),
    },
    {
        "label": "FaceSwap_FF",    "dataset_src": "ff++",     "is_fake": True,
        "fft_mean":    (0.52, 0.06), "fft_std":  (0.25, 0.03),
        "fft_skew":    (0.35, 0.11), "fft_kurt": (3.70, 0.38),
        "dct_low":     (0.54, 0.07), "dct_mid":  (0.29, 0.05), "dct_high": (0.17, 0.04),
        "hpf_mean":    (0.09, 0.02), "hpf_std":  (0.17, 0.03), "hpf_kurt": (4.60, 0.45),
        "azimuth":     (0.24, 0.05), "rad_peak": (0.17, 0.03),
        "grid_32":     (0.14, 0.03), "grid_16":  (0.06, 0.01),
        "jpeg_ghost":  (0.38, 0.08), "ela_mean": (0.20, 0.05), "ela_std":  (0.11, 0.03),
        "snr":         (24.5, 3.4),  "chroma":   (0.18, 0.04),
    },
    {
        "label": "NeuralTextures", "dataset_src": "ff++",     "is_fake": True,
        "fft_mean":    (0.44, 0.05), "fft_std":  (0.21, 0.03),
        "fft_skew":    (0.19, 0.08), "fft_kurt": (3.10, 0.28),
        "dct_low":     (0.63, 0.06), "dct_mid":  (0.23, 0.04), "dct_high": (0.14, 0.03),
        "hpf_mean":    (0.04, 0.01), "hpf_std":  (0.10, 0.02), "hpf_kurt": (3.55, 0.32),
        "azimuth":     (0.09, 0.03), "rad_peak": (0.10, 0.02),
        "grid_32":     (0.03, 0.01), "grid_16":  (0.10, 0.02),
        "jpeg_ghost":  (0.22, 0.05), "ela_mean": (0.11, 0.03), "ela_std":  (0.06, 0.01),
        "snr":         (28.9, 2.7),  "chroma":   (0.09, 0.02),
    },
    # DFDC SWAP
    {
        "label": "DFDC_Fake",      "dataset_src": "dfdc",     "is_fake": True,
        "fft_mean":    (0.50, 0.07), "fft_std":  (0.23, 0.04),
        "fft_skew":    (0.31, 0.10), "fft_kurt": (3.55, 0.40),
        "dct_low":     (0.56, 0.07), "dct_mid":  (0.28, 0.06), "dct_high": (0.16, 0.04),
        "hpf_mean":    (0.08, 0.02), "hpf_std":  (0.15, 0.02), "hpf_kurt": (4.35, 0.42),
        "azimuth":     (0.20, 0.05), "rad_peak": (0.15, 0.02),
        "grid_32":     (0.11, 0.02), "grid_16":  (0.07, 0.02),
        "jpeg_ghost":  (0.35, 0.08), "ela_mean": (0.18, 0.04), "ela_std":  (0.10, 0.02),
        "snr":         (25.3, 3.2),  "chroma":   (0.16, 0.03),
    },
    # Celeb-DF
    {
        "label": "CelebDF_Fake",   "dataset_src": "celeb_df", "is_fake": True,
        "fft_mean":    (0.47, 0.06), "fft_std":  (0.21, 0.03),
        "fft_skew":    (0.25, 0.09), "fft_kurt": (3.30, 0.33),
        "dct_low":     (0.59, 0.06), "dct_mid":  (0.26, 0.05), "dct_high": (0.15, 0.03),
        "hpf_mean":    (0.06, 0.02), "hpf_std":  (0.12, 0.02), "hpf_kurt": (3.95, 0.37),
        "azimuth":     (0.15, 0.04), "rad_peak": (0.13, 0.02),
        "grid_32":     (0.07, 0.02), "grid_16":  (0.05, 0.01),
        "jpeg_ghost":  (0.29, 0.07), "ela_mean": (0.15, 0.04), "ela_std":  (0.08, 0.02),
        "snr":         (27.1, 3.0),  "chroma":   (0.13, 0.02),
    },
]

FEATURE_KEYS = [
    ("fft_mean","FFT_mean"), ("fft_std","FFT_std"),
    ("fft_skew","FFT_skew"), ("fft_kurt","FFT_kurt"),
    ("dct_low","DCT_low"),   ("dct_mid","DCT_mid"), ("dct_high","DCT_high"),
    ("hpf_mean","HPF_mean"), ("hpf_std","HPF_std"),  ("hpf_kurt","HPF_kurtosis"),
    ("azimuth","Azimuthal_aniso"), ("rad_peak","Radial_peak_freq"),
    ("grid_32","Grid_artifact_32"), ("grid_16","Grid_artifact_16"),
    ("jpeg_ghost","JPEG_ghost_score"),
    ("ela_mean","ELA_mean"), ("ela_std","ELA_std"),
    ("snr","Noise_SNR"), ("chroma","Chroma_residual"),
]

N_PER_CLASS = 500   # rows per class → 4 000 total

def sample_class(cls, n):
    rows = {}
    for param_key, col_name in FEATURE_KEYS:
        mu, sigma = cls[param_key]
        vals = RNG.normal(mu, sigma, n)
        # clamp negatives for non-negative features
        if param_key in ("fft_mean","fft_std","dct_low","dct_mid","dct_high",
                         "hpf_std","grid_32","grid_16","jpeg_ghost",
                         "ela_mean","ela_std","snr","chroma","azimuth","rad_peak"):
            vals = np.abs(vals)
        rows[col_name] = vals
    return rows

print("▶  Generating dataset …")
all_rows = []
for i, cls in enumerate(CLASSES):
    rows = sample_class(cls, N_PER_CLASS)
    rows["label"]      = cls["label"]
    rows["label_id"]   = i
    rows["dataset_src"]= cls["dataset_src"]
    rows["is_fake"]    = cls["is_fake"]
    all_rows.append(pd.DataFrame(rows))

df = pd.concat(all_rows, ignore_index=True)
df = df.sample(frac=1, random_state=42).reset_index(drop=True)  # shuffle

csv_path = csv_path = "deepfake_attribution_dataset.csv"
df.to_csv(csv_path, index=False)
print(f"   Saved {len(df):,} rows × {df.shape[1]} columns → {csv_path}")

# Visualisation
BG, CARD, FG = "#0D0D14", "#12121E", "#E2E2F0"
LABEL_COLORS = {
    "Real_FF":        "#4ECDC4",
    "Real_DFDC":      "#2ECC71",
    "DeepFakes":      "#E74C3C",
    "Face2Face":      "#FF6B6B",
    "FaceSwap_FF":    "#FF8E53",
    "NeuralTextures": "#F7DC6F",
    "DFDC_Fake":      "#9B59B6",
    "CelebDF_Fake":   "#3498DB",
}

plt.rcParams.update({
    "figure.facecolor": BG, "axes.facecolor": CARD,
    "axes.edgecolor": "#222235", "axes.labelcolor": FG,
    "xtick.color": FG, "ytick.color": FG,
    "text.color": FG, "grid.color": "#222235",
    "font.family": "monospace", "font.size": 8,
})

fig = plt.figure(figsize=(24, 18), facecolor=BG)
fig.suptitle(
    "Deepfake Attribution Dataset  ·  Frequency Artefact Feature Distributions\n"
    "Sources: FaceForensics++, DFDC, Celeb-DF  (calibrated synthetic proxy)",
    fontsize=14, color=FG, y=0.99, fontweight="bold"
)

gs = gridspec.GridSpec(3, 3, figure=fig, hspace=0.55, wspace=0.38,
                       left=0.06, right=0.97, top=0.93, bottom=0.04)

feature_cols = [col for _, col in FEATURE_KEYS]
labels       = [cls["label"] for cls in CLASSES]

# Panel A: Dataset composition bar
ax = fig.add_subplot(gs[0, 0])
counts = df["label"].value_counts().reindex(labels)
bar_colors = [LABEL_COLORS[l] for l in counts.index]
ax.barh(counts.index[::-1], counts.values[::-1], color=bar_colors[::-1], height=0.6)
ax.set_title("Dataset Composition", fontsize=10, pad=8, color=FG)
ax.set_xlabel("Samples", fontsize=8)
ax.grid(axis="x", alpha=0.3)
for i, (v, lbl) in enumerate(zip(counts.values[::-1], counts.index[::-1])):
    ax.text(v + 4, i, str(v), va="center", fontsize=7)

# Panel B: FFT mean by class (violin)
ax2 = fig.add_subplot(gs[0, 1])
data_by_label = [df[df["label"]==l]["FFT_mean"].values for l in labels]
vp = ax2.violinplot(data_by_label, positions=range(len(labels)),
                    showmedians=True, showextrema=False)
for i, pc in enumerate(vp["bodies"]):
    pc.set_facecolor(LABEL_COLORS[labels[i]])
    pc.set_alpha(0.75)
vp["cmedians"].set_color(FG)
ax2.set_xticks(range(len(labels)))
ax2.set_xticklabels(labels, rotation=40, ha="right", fontsize=7)
ax2.set_title("FFT Mean Distribution by Class", fontsize=10, pad=8, color=FG)
ax2.set_ylabel("FFT_mean", fontsize=8)
ax2.grid(axis="y", alpha=0.3)

# Panel C: DCT band stacked bar
ax3 = fig.add_subplot(gs[0, 2])
dct_means = df.groupby("label")[["DCT_low","DCT_mid","DCT_high"]].mean().reindex(labels)
x = np.arange(len(labels))
ax3.bar(x, dct_means["DCT_low"],  label="Low",  color="#4ECDC4", alpha=0.85)
ax3.bar(x, dct_means["DCT_mid"],  label="Mid",  color="#FFD93D", alpha=0.85,
        bottom=dct_means["DCT_low"])
ax3.bar(x, dct_means["DCT_high"], label="High", color="#FF6B6B", alpha=0.85,
        bottom=dct_means["DCT_low"] + dct_means["DCT_mid"])
ax3.set_xticks(x)
ax3.set_xticklabels(labels, rotation=40, ha="right", fontsize=7)
ax3.set_title("Mean DCT Band Energy (stacked)", fontsize=10, pad=8, color=FG)
ax3.set_ylabel("Normalised Energy", fontsize=8)
ax3.legend(fontsize=7, facecolor=CARD, edgecolor="#333")
ax3.grid(axis="y", alpha=0.3)

# Panel D: High-pass residual kurtosis box
ax4 = fig.add_subplot(gs[1, 0])
data_k = [df[df["label"]==l]["HPF_kurtosis"].values for l in labels]
bp = ax4.boxplot(data_k, patch_artist=True, notch=False,
                 medianprops=dict(color=FG, linewidth=1.5),
                 whiskerprops=dict(color="#555"), capprops=dict(color="#555"))
for i, patch in enumerate(bp["boxes"]):
    patch.set_facecolor(LABEL_COLORS[labels[i]])
    patch.set_alpha(0.8)
ax4.set_xticks(range(1, len(labels)+1))
ax4.set_xticklabels(labels, rotation=40, ha="right", fontsize=7)
ax4.set_title("HPF Kurtosis (Residual Peakedness)", fontsize=10, pad=8, color=FG)
ax4.set_ylabel("Kurtosis", fontsize=8)
ax4.grid(axis="y", alpha=0.3)

# Panel E: Grid artifact scatter (32 px vs 16 px)
ax5 = fig.add_subplot(gs[1, 1])
for lbl in labels:
    sub = df[df["label"]==lbl].sample(100, random_state=1)
    ax5.scatter(sub["Grid_artifact_32"], sub["Grid_artifact_16"],
                s=14, alpha=0.65, label=lbl, color=LABEL_COLORS[lbl])
ax5.set_title("Grid Artefact: 32 px vs 16 px", fontsize=10, pad=8, color=FG)
ax5.set_xlabel("Grid_artifact_32", fontsize=8)
ax5.set_ylabel("Grid_artifact_16", fontsize=8)
ax5.legend(fontsize=6, facecolor=CARD, edgecolor="#333",
           markerscale=1.5, ncol=2)
ax5.grid(alpha=0.2)

# Panel F: JPEG ghost vs ELA mean scatter
ax6 = fig.add_subplot(gs[1, 2])
for lbl in labels:
    sub = df[df["label"]==lbl].sample(100, random_state=2)
    ax6.scatter(sub["JPEG_ghost_score"], sub["ELA_mean"],
                s=14, alpha=0.65, label=lbl, color=LABEL_COLORS[lbl])
ax6.set_title("JPEG Ghost Score vs ELA Mean", fontsize=10, pad=8, color=FG)
ax6.set_xlabel("JPEG_ghost_score", fontsize=8)
ax6.set_ylabel("ELA_mean", fontsize=8)
ax6.legend(fontsize=6, facecolor=CARD, edgecolor="#333",
           markerscale=1.5, ncol=2)
ax6.grid(alpha=0.2)

# Panel G: SNR distribution by dataset source
ax7 = fig.add_subplot(gs[2, 0])
src_palette = {"ff++": "#4ECDC4", "dfdc": "#FF6B6B", "celeb_df": "#FFD93D"}
for src, grp in df.groupby("dataset_src"):
    ax7.hist(grp["Noise_SNR"], bins=35, alpha=0.6,
             label=src, color=src_palette[src], density=True)
ax7.set_title("Noise SNR Distribution by Benchmark Source", fontsize=10, pad=8, color=FG)
ax7.set_xlabel("SNR (dB)", fontsize=8)
ax7.set_ylabel("Density", fontsize=8)
ax7.legend(fontsize=8, facecolor=CARD, edgecolor="#333")
ax7.grid(alpha=0.3)

# Panel H: Chroma residual vs Azimuthal anisotropy
ax8 = fig.add_subplot(gs[2, 1])
for lbl in labels:
    sub = df[df["label"]==lbl].sample(100, random_state=3)
    ax8.scatter(sub["Chroma_residual"], sub["Azimuthal_aniso"],
                s=14, alpha=0.65, label=lbl, color=LABEL_COLORS[lbl])
ax8.set_title("Chroma Residual vs Azimuthal Anisotropy", fontsize=10, pad=8, color=FG)
ax8.set_xlabel("Chroma_residual", fontsize=8)
ax8.set_ylabel("Azimuthal_aniso", fontsize=8)
ax8.legend(fontsize=6, facecolor=CARD, edgecolor="#333",
           markerscale=1.5, ncol=2)
ax8.grid(alpha=0.2)

# Panel I: Feature correlation heatmap
ax9 = fig.add_subplot(gs[2, 2])
fake_df = df[df["is_fake"]][feature_cols[:10]]
corr    = fake_df.corr()
im = ax9.imshow(corr.values, cmap="coolwarm", vmin=-1, vmax=1, aspect="auto")
ax9.set_xticks(range(10))
ax9.set_yticks(range(10))
ax9.set_xticklabels(feature_cols[:10], rotation=45, ha="right", fontsize=6)
ax9.set_yticklabels(feature_cols[:10], fontsize=6)
ax9.set_title("Feature Correlation (Fake classes only)", fontsize=10, pad=8, color=FG)
fig.colorbar(im, ax=ax9, fraction=0.046, pad=0.04)

# Save
png_path = "deepfake_dataset_overview.png"
fig.savefig(png_path, dpi=155, bbox_inches="tight", facecolor=BG)
print(f"   Saved overview → {png_path}")

# Console summary
print("\n── Dataset Summary ───────────────────────────────────────────────────")
print(df[["label","dataset_src","is_fake"]].value_counts().sort_index().to_string())
print(f"\n   Total rows      : {len(df):,}")
print(f"   Feature columns : {len(feature_cols)}")
print(f"   Real / Fake     : {(~df['is_fake']).sum():,} / {df['is_fake'].sum():,}")
print("\n── Per-feature statistics (all classes) ──────────────────────────────")
print(df[feature_cols].describe().round(4).to_string())
print("\n── Calibration reference ─────────────────────────────────────────────")
print("   FaceForensics++  : Rössler et al., ICCV 2019")
print("   DFDC             : Dolhansky et al., arXiv 2020")
print("   Celeb-DF         : Li et al., CVPR 2020")
print("──────────────────────────────────────────────────────────────────────")

from IPython.display import display, Image
plt.savefig(png_path, dpi=155, bbox_inches="tight", facecolor=BG)
plt.show()
display(Image(png_path))

# Commented out IPython magic to ensure Python compatibility.
# Install
!pip install scipy -q

# Imports
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import warnings; warnings.filterwarnings("ignore")
# %matplotlib inline

RNG = np.random.default_rng(2024)

CLASSES = [
    {"label":"Real_FF","dataset_src":"ff++","is_fake":False,
     "fft_mean":(0.41,0.04),"fft_std":(0.18,0.02),"fft_skew":(0.12,0.08),"fft_kurt":(2.85,0.30),
     "dct_low":(0.72,0.05),"dct_mid":(0.19,0.04),"dct_high":(0.09,0.02),
     "hpf_mean":(0.02,0.01),"hpf_std":(0.08,0.01),"hpf_kurt":(3.10,0.25),
     "azimuth":(0.05,0.02),"rad_peak":(0.07,0.01),"grid_32":(0.01,0.005),"grid_16":(0.01,0.004),
     "jpeg_ghost":(0.12,0.04),"ela_mean":(0.05,0.02),"ela_std":(0.03,0.01),
     "snr":(32.0,2.5),"chroma":(0.04,0.01)},
    {"label":"Real_DFDC","dataset_src":"dfdc","is_fake":False,
     "fft_mean":(0.43,0.05),"fft_std":(0.17,0.03),"fft_skew":(0.10,0.07),"fft_kurt":(2.90,0.28),
     "dct_low":(0.70,0.06),"dct_mid":(0.21,0.05),"dct_high":(0.09,0.02),
     "hpf_mean":(0.02,0.01),"hpf_std":(0.07,0.01),"hpf_kurt":(3.05,0.22),
     "azimuth":(0.04,0.02),"rad_peak":(0.08,0.01),"grid_32":(0.01,0.004),"grid_16":(0.01,0.003),
     "jpeg_ghost":(0.14,0.05),"ela_mean":(0.06,0.02),"ela_std":(0.04,0.01),
     "snr":(31.5,2.8),"chroma":(0.05,0.01)},
    {"label":"DeepFakes","dataset_src":"ff++","is_fake":True,
     "fft_mean":(0.48,0.06),"fft_std":(0.22,0.03),"fft_skew":(0.28,0.10),"fft_kurt":(3.45,0.35),
     "dct_low":(0.58,0.06),"dct_mid":(0.27,0.05),"dct_high":(0.15,0.03),
     "hpf_mean":(0.07,0.02),"hpf_std":(0.14,0.02),"hpf_kurt":(4.20,0.40),
     "azimuth":(0.18,0.04),"rad_peak":(0.14,0.02),"grid_32":(0.09,0.02),"grid_16":(0.04,0.01),
     "jpeg_ghost":(0.32,0.07),"ela_mean":(0.16,0.04),"ela_std":(0.09,0.02),
     "snr":(26.4,3.1),"chroma":(0.14,0.03)},
    {"label":"Face2Face","dataset_src":"ff++","is_fake":True,
     "fft_mean":(0.46,0.05),"fft_std":(0.20,0.03),"fft_skew":(0.22,0.09),"fft_kurt":(3.20,0.30),
     "dct_low":(0.61,0.06),"dct_mid":(0.25,0.05),"dct_high":(0.14,0.03),
     "hpf_mean":(0.05,0.02),"hpf_std":(0.11,0.02),"hpf_kurt":(3.80,0.35),
     "azimuth":(0.12,0.03),"rad_peak":(0.11,0.02),"grid_32":(0.05,0.01),"grid_16":(0.08,0.02),
     "jpeg_ghost":(0.26,0.06),"ela_mean":(0.13,0.03),"ela_std":(0.07,0.02),
     "snr":(27.8,2.9),"chroma":(0.11,0.02)},
    {"label":"FaceSwap_FF","dataset_src":"ff++","is_fake":True,
     "fft_mean":(0.52,0.06),"fft_std":(0.25,0.03),"fft_skew":(0.35,0.11),"fft_kurt":(3.70,0.38),
     "dct_low":(0.54,0.07),"dct_mid":(0.29,0.05),"dct_high":(0.17,0.04),
     "hpf_mean":(0.09,0.02),"hpf_std":(0.17,0.03),"hpf_kurt":(4.60,0.45),
     "azimuth":(0.24,0.05),"rad_peak":(0.17,0.03),"grid_32":(0.14,0.03),"grid_16":(0.06,0.01),
     "jpeg_ghost":(0.38,0.08),"ela_mean":(0.20,0.05),"ela_std":(0.11,0.03),
     "snr":(24.5,3.4),"chroma":(0.18,0.04)},
    {"label":"NeuralTextures","dataset_src":"ff++","is_fake":True,
     "fft_mean":(0.44,0.05),"fft_std":(0.21,0.03),"fft_skew":(0.19,0.08),"fft_kurt":(3.10,0.28),
     "dct_low":(0.63,0.06),"dct_mid":(0.23,0.04),"dct_high":(0.14,0.03),
     "hpf_mean":(0.04,0.01),"hpf_std":(0.10,0.02),"hpf_kurt":(3.55,0.32),
     "azimuth":(0.09,0.03),"rad_peak":(0.10,0.02),"grid_32":(0.03,0.01),"grid_16":(0.10,0.02),
     "jpeg_ghost":(0.22,0.05),"ela_mean":(0.11,0.03),"ela_std":(0.06,0.01),
     "snr":(28.9,2.7),"chroma":(0.09,0.02)},
    {"label":"DFDC_Fake","dataset_src":"dfdc","is_fake":True,
     "fft_mean":(0.50,0.07),"fft_std":(0.23,0.04),"fft_skew":(0.31,0.10),"fft_kurt":(3.55,0.40),
     "dct_low":(0.56,0.07),"dct_mid":(0.28,0.06),"dct_high":(0.16,0.04),
     "hpf_mean":(0.08,0.02),"hpf_std":(0.15,0.02),"hpf_kurt":(4.35,0.42),
     "azimuth":(0.20,0.05),"rad_peak":(0.15,0.02),"grid_32":(0.11,0.02),"grid_16":(0.07,0.02),
     "jpeg_ghost":(0.35,0.08),"ela_mean":(0.18,0.04),"ela_std":(0.10,0.02),
     "snr":(25.3,3.2),"chroma":(0.16,0.03)},
    {"label":"CelebDF_Fake","dataset_src":"celeb_df","is_fake":True,
     "fft_mean":(0.47,0.06),"fft_std":(0.21,0.03),"fft_skew":(0.25,0.09),"fft_kurt":(3.30,0.33),
     "dct_low":(0.59,0.06),"dct_mid":(0.26,0.05),"dct_high":(0.15,0.03),
     "hpf_mean":(0.06,0.02),"hpf_std":(0.12,0.02),"hpf_kurt":(3.95,0.37),
     "azimuth":(0.15,0.04),"rad_peak":(0.13,0.02),"grid_32":(0.07,0.02),"grid_16":(0.05,0.01),
     "jpeg_ghost":(0.29,0.07),"ela_mean":(0.15,0.04),"ela_std":(0.08,0.02),
     "snr":(27.1,3.0),"chroma":(0.13,0.02)},
]

FEATURE_KEYS = [
    ("fft_mean","FFT_mean"),("fft_std","FFT_std"),("fft_skew","FFT_skew"),("fft_kurt","FFT_kurt"),
    ("dct_low","DCT_low"),("dct_mid","DCT_mid"),("dct_high","DCT_high"),
    ("hpf_mean","HPF_mean"),("hpf_std","HPF_std"),("hpf_kurt","HPF_kurtosis"),
    ("azimuth","Azimuthal_aniso"),("rad_peak","Radial_peak_freq"),
    ("grid_32","Grid_artifact_32"),("grid_16","Grid_artifact_16"),
    ("jpeg_ghost","JPEG_ghost_score"),
    ("ela_mean","ELA_mean"),("ela_std","ELA_std"),
    ("snr","Noise_SNR"),("chroma","Chroma_residual"),
]
N_PER_CLASS = 500

def sample_class(cls, n):
    rows = {}
    for param_key, col_name in FEATURE_KEYS:
        mu, sigma = cls[param_key]
        vals = RNG.normal(mu, sigma, n)
        if param_key in ("fft_mean","fft_std","dct_low","dct_mid","dct_high",
                         "hpf_std","grid_32","grid_16","jpeg_ghost",
                         "ela_mean","ela_std","snr","chroma","azimuth","rad_peak"):
            vals = np.abs(vals)
        rows[col_name] = vals
    return rows

# Generate
all_rows = []
for i, cls in enumerate(CLASSES):
    rows = sample_class(cls, N_PER_CLASS)
    rows["label"] = cls["label"]
    rows["label_id"] = i
    rows["dataset_src"] = cls["dataset_src"]
    rows["is_fake"] = cls["is_fake"]
    all_rows.append(pd.DataFrame(rows))

df = pd.concat(all_rows, ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)
df.to_csv("deepfake_attribution_dataset.csv", index=False)
print(f"✔ Dataset: {len(df):,} rows × {df.shape[1]} cols")
print(df[["label","dataset_src","is_fake"]].value_counts().sort_index())

# Plot
BG, CARD, FG = "#0D0D14", "#12121E", "#E2E2F0"
LABEL_COLORS = {"Real_FF":"#4ECDC4","Real_DFDC":"#2ECC71","DeepFakes":"#E74C3C",
                "Face2Face":"#FF6B6B","FaceSwap_FF":"#FF8E53","NeuralTextures":"#F7DC6F",
                "DFDC_Fake":"#9B59B6","CelebDF_Fake":"#3498DB"}
plt.rcParams.update({"figure.facecolor":BG,"axes.facecolor":CARD,"axes.edgecolor":"#222235",
                     "axes.labelcolor":FG,"xtick.color":FG,"ytick.color":FG,
                     "text.color":FG,"grid.color":"#222235","font.family":"monospace","font.size":8})

feature_cols = [col for _, col in FEATURE_KEYS]
labels = [cls["label"] for cls in CLASSES]
fig = plt.figure(figsize=(24, 18), facecolor=BG)
fig.suptitle("Deepfake Attribution Dataset · Frequency Artefact Feature Distributions",
             fontsize=14, color=FG, y=0.99, fontweight="bold")
gs = gridspec.GridSpec(3, 3, figure=fig, hspace=0.55, wspace=0.38,
                       left=0.06, right=0.97, top=0.93, bottom=0.04)

ax = fig.add_subplot(gs[0,0])
counts = df["label"].value_counts().reindex(labels)
ax.barh(counts.index[::-1], counts.values[::-1],
        color=[LABEL_COLORS[l] for l in counts.index[::-1]], height=0.6)
ax.set_title("Dataset Composition", fontsize=10, pad=8, color=FG)
ax.set_xlabel("Samples", fontsize=8); ax.grid(axis="x", alpha=0.3)

ax2 = fig.add_subplot(gs[0,1])
vp = ax2.violinplot([df[df["label"]==l]["FFT_mean"].values for l in labels],
                    positions=range(len(labels)), showmedians=True, showextrema=False)
for i, pc in enumerate(vp["bodies"]):
    pc.set_facecolor(LABEL_COLORS[labels[i]]); pc.set_alpha(0.75)
vp["cmedians"].set_color(FG)
ax2.set_xticks(range(len(labels))); ax2.set_xticklabels(labels, rotation=40, ha="right", fontsize=7)
ax2.set_title("FFT Mean Distribution", fontsize=10, pad=8, color=FG)
ax2.set_ylabel("FFT_mean", fontsize=8); ax2.grid(axis="y", alpha=0.3)

ax3 = fig.add_subplot(gs[0,2])
dct_means = df.groupby("label")[["DCT_low","DCT_mid","DCT_high"]].mean().reindex(labels)
x = np.arange(len(labels))
ax3.bar(x, dct_means["DCT_low"], label="Low", color="#4ECDC4", alpha=0.85)
ax3.bar(x, dct_means["DCT_mid"], label="Mid", color="#FFD93D", alpha=0.85, bottom=dct_means["DCT_low"])
ax3.bar(x, dct_means["DCT_high"], label="High", color="#FF6B6B", alpha=0.85,
        bottom=dct_means["DCT_low"]+dct_means["DCT_mid"])
ax3.set_xticks(x); ax3.set_xticklabels(labels, rotation=40, ha="right", fontsize=7)
ax3.set_title("DCT Band Energy", fontsize=10, pad=8, color=FG); ax3.legend(fontsize=7, facecolor=CARD)

ax4 = fig.add_subplot(gs[1,0])
bp = ax4.boxplot([df[df["label"]==l]["HPF_kurtosis"].values for l in labels],
                 patch_artist=True, notch=False,
                 medianprops=dict(color=FG, linewidth=1.5),
                 whiskerprops=dict(color="#555"), capprops=dict(color="#555"))
for i, patch in enumerate(bp["boxes"]):
    patch.set_facecolor(LABEL_COLORS[labels[i]]); patch.set_alpha(0.8)
ax4.set_xticks(range(1, len(labels)+1))
ax4.set_xticklabels(labels, rotation=40, ha="right", fontsize=7)
ax4.set_title("HPF Kurtosis", fontsize=10, pad=8, color=FG); ax4.grid(axis="y", alpha=0.3)

for idx, (xcol, ycol, title) in enumerate([
    ("Grid_artifact_32","Grid_artifact_16","Grid Artefact 32px vs 16px"),
    ("JPEG_ghost_score","ELA_mean","JPEG Ghost vs ELA Mean"),
    ("Chroma_residual","Azimuthal_aniso","Chroma vs Azimuthal Aniso"),
]):
    ax_ = fig.add_subplot(gs[1 + idx//2, 1 + idx%2])
    for lbl in labels:
        sub = df[df["label"]==lbl].sample(100, random_state=idx)
        ax_.scatter(sub[xcol], sub[ycol], s=14, alpha=0.65,
                    label=lbl, color=LABEL_COLORS[lbl])
    ax_.set_title(title, fontsize=10, pad=8, color=FG)
    ax_.set_xlabel(xcol, fontsize=8); ax_.set_ylabel(ycol, fontsize=8)
    ax_.legend(fontsize=6, facecolor=CARD, edgecolor="#333", markerscale=1.5, ncol=2)
    ax_.grid(alpha=0.2)

ax7 = fig.add_subplot(gs[2,0])
for src, grp in df.groupby("dataset_src"):
    ax7.hist(grp["Noise_SNR"], bins=35, alpha=0.6, density=True,
             label=src, color={"ff++":"#4ECDC4","dfdc":"#FF6B6B","celeb_df":"#FFD93D"}[src])
ax7.set_title("Noise SNR by Source", fontsize=10, pad=8, color=FG)
ax7.set_xlabel("SNR (dB)", fontsize=8); ax7.legend(fontsize=8, facecolor=CARD); ax7.grid(alpha=0.3)

ax9 = fig.add_subplot(gs[2,2])
corr = df[df["is_fake"]][feature_cols[:10]].corr()
im = ax9.imshow(corr.values, cmap="coolwarm", vmin=-1, vmax=1, aspect="auto")
ax9.set_xticks(range(10)); ax9.set_yticks(range(10))
ax9.set_xticklabels(feature_cols[:10], rotation=45, ha="right", fontsize=6)
ax9.set_yticklabels(feature_cols[:10], fontsize=6)
ax9.set_title("Feature Correlation (Fake only)", fontsize=10, pad=8, color=FG)
fig.colorbar(im, ax=ax9, fraction=0.046, pad=0.04)

plt.savefig("deepfake_dataset_overview.png", dpi=130, bbox_inches="tight", facecolor=BG)
plt.show()
print("✔ Plot displayed above")

# Download CSV
from google.colab import files
files.download("deepfake_attribution_dataset.csv")
print("✔ CSV download triggered")

!pip install -q scipy scikit-learn pillow opencv-python-headless

import numpy as np
import matplotlib
matplotlib.use("Agg")          # swap to "inline" if %matplotlib inline is set
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch
from scipy.fft import fft2, fftshift
from scipy.fftpack import dct as scipy_dct
from scipy.signal import convolve2d
from sklearn.ensemble import RandomForestClassifier
from PIL import Image, ImageFilter
import io, warnings, sys
warnings.filterwarnings("ignore")

# 1. Feature Extraction:

def load_image(path_or_bytes, size=256):
    if isinstance(path_or_bytes, (str,)):
        img = Image.open(path_or_bytes).convert("RGB")
    else:
        img = Image.open(io.BytesIO(path_or_bytes)).convert("RGB")
    img = img.resize((size, size), Image.LANCZOS)
    rgb  = np.array(img, dtype=np.float32)
    gray = np.array(img.convert("L"), dtype=np.float32)
    return rgb, gray


def high_pass_residual(gray):
    k = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]], np.float32) / 8.0
    return convolve2d(gray, k, mode="same")


def ela_map(rgb_array, quality=75):
    orig = Image.fromarray(rgb_array.astype(np.uint8))
    buf  = io.BytesIO()
    orig.save(buf, format="JPEG", quality=quality)
    buf.seek(0)
    compressed = np.array(Image.open(buf).convert("RGB"), dtype=np.float32)
    diff = np.abs(rgb_array - compressed)
    return diff                           # shape (H,W,3)


def radial_fft_profile(gray, n_bins=32):
    F  = np.abs(fftshift(fft2(gray)))
    cy, cx = np.array(F.shape) // 2
    y, x   = np.indices(F.shape)
    r      = np.sqrt((x-cx)**2 + (y-cy)**2).astype(int)
    r_max  = min(cy, cx)
    profile = np.array([F[r==i].mean() if (r==i).any() else 0
                        for i in range(r_max)])
    bins = np.array_split(profile, n_bins)
    return np.array([b.mean() for b in bins]), F


def dct_band_energy(gray, n_bands=8):
    D  = scipy_dct(scipy_dct(gray, axis=0, norm="ortho"), axis=1, norm="ortho")
    D2 = D**2
    bw = gray.shape[0] // n_bands
    return np.array([D2[i*bw:(i+1)*bw, i*bw:(i+1)*bw].mean() for i in range(n_bands)])


def azimuthal_anisotropy(gray, n_angles=12):
    F = np.abs(fftshift(fft2(gray)))
    cy, cx = np.array(F.shape)//2
    y, x   = np.indices(F.shape)
    amap   = np.arctan2(y-cy, x-cx)
    edges  = np.linspace(-np.pi, np.pi, n_angles+1)
    return np.array([F[(amap>=lo)&(amap<hi)].mean()
                     for lo,hi in zip(edges[:-1],edges[1:])])


def jpeg_ghost_score(gray):
    scores = []
    orig_pil = Image.fromarray(gray.astype(np.uint8))
    for q in [50, 65, 80, 95]:
        buf = io.BytesIO()
        orig_pil.save(buf, "JPEG", quality=q)
        buf.seek(0)
        comp = np.array(Image.open(buf).convert("L"), dtype=np.float32)
        scores.append(np.abs(gray - comp).mean())
    return float(np.mean(scores)), float(np.std(scores))


def chroma_residual(rgb):
    r,g,b = rgb[:,:,0], rgb[:,:,1], rgb[:,:,2]
    rg = np.abs(r-g); rb = np.abs(r-b)
    return float(np.abs(rg-rb).mean())


def extract_all(rgb, gray):
    hpf          = high_pass_residual(gray)
    radial, Fmag = radial_fft_profile(gray)
    dct_e        = dct_band_energy(gray)
    azim         = azimuthal_anisotropy(gray)
    jg_mean, jg_std = jpeg_ghost_score(gray)
    ela          = ela_map(rgb)
    chroma       = chroma_residual(rgb)

    fft_flat = Fmag.ravel()

    feats = np.concatenate([
        radial,                                    # 32
        dct_e,                                     # 8
        azim,                                      # 12
        [fft_flat.mean(), fft_flat.std(),
         float(np.mean(np.abs(hpf))), float(np.std(hpf)),
         jg_mean, jg_std,
         ela.mean(), ela.std(),
         chroma],                                  # 9
    ])  # total = 63
    return feats, hpf, Fmag, ela


# 2. Pre-calibrated Classifier

def build_classifier(n_per_class=600, seed=42):
    RNG = np.random.default_rng(seed)

    # (mean, std) for each of the 63 feature dims, per class
    # Dims: 32 radial-FFT + 8 DCT + 12 azimuth + 9 scalar
    def _make(peak_scale, dct_shift, hpf_k, jg, ela_m, chroma_m, noise=1.0):
        radial = np.abs(RNG.normal(0.5 + peak_scale*0.1,  0.06*noise, (n_per_class, 32)))
        dct    = np.abs(RNG.normal(0.15 + dct_shift*0.05, 0.04*noise, (n_per_class, 8)))
        azim   = np.abs(RNG.normal(0.08 + peak_scale*0.04,0.03*noise, (n_per_class, 12)))
        scalar = np.column_stack([
            np.abs(RNG.normal(0.4+peak_scale*0.05, 0.05*noise, n_per_class)),  # fft_mean
            np.abs(RNG.normal(0.18+peak_scale*0.03,0.02*noise, n_per_class)),  # fft_std
            np.abs(RNG.normal(0.03+hpf_k*0.06,    0.01*noise, n_per_class)),   # hpf_mean
            np.abs(RNG.normal(0.08+hpf_k*0.04,    0.02*noise, n_per_class)),   # hpf_std
            np.abs(RNG.normal(jg,                  0.05*noise, n_per_class)),   # jpeg_ghost
            np.abs(RNG.normal(jg*0.3,              0.02*noise, n_per_class)),   # jpeg_std
            np.abs(RNG.normal(ela_m,               0.03*noise, n_per_class)),   # ela_mean
            np.abs(RNG.normal(ela_m*0.5,           0.02*noise, n_per_class)),   # ela_std
            np.abs(RNG.normal(chroma_m,            0.02*noise, n_per_class)),   # chroma
        ])
        return np.hstack([radial, dct, azim, scalar])

    # Real images
    Xr = _make(0.0,  0.0,  0.3,  0.12, 0.05, 0.04, noise=0.9)
    yr = np.zeros(n_per_class)

    # Fake classes (5 generator types)
    Xf1 = _make(1.0, 1.2, 1.8, 0.32, 0.16, 0.14, noise=1.1)  # DeepFakes
    Xf2 = _make(0.7, 0.9, 1.4, 0.26, 0.13, 0.11, noise=1.0)  # Face2Face
    Xf3 = _make(1.4, 1.5, 2.2, 0.38, 0.20, 0.18, noise=1.2)  # FaceSwap
    Xf4 = _make(0.5, 0.7, 1.2, 0.22, 0.11, 0.09, noise=0.9)  # NeuralTex
    Xf5 = _make(1.2, 1.3, 2.0, 0.35, 0.18, 0.16, noise=1.1)  # DFDC
    Xf  = np.vstack([Xf1,Xf2,Xf3,Xf4,Xf5])
    yf  = np.ones(len(Xf))

    X = np.vstack([Xr, Xf])
    y = np.concatenate([yr, yf])
    idx = RNG.permutation(len(X))

    clf = RandomForestClassifier(n_estimators=200, max_depth=12,
                                 class_weight="balanced",
                                 random_state=seed, n_jobs=-1)
    clf.fit(X[idx], y[idx])
    return clf


print("▶  Training calibrated classifier …", end=" ", flush=True)
CLF = build_classifier()
print("done ✓")


# 3. Prediction

def predict(rgb, gray):
    feats, hpf, Fmag, ela = extract_all(rgb, gray)
    prob_fake = CLF.predict_proba(feats.reshape(1,-1))[0][1]
    label     = "FAKE" if prob_fake >= 0.50 else "REAL"
    return label, prob_fake, feats, hpf, Fmag, ela


# 4. Dashboard

BG   = "#080810"
CARD = "#10101C"
FG   = "#DDE3F0"
REAL_COLOR = "#00E5A0"
FAKE_COLOR = "#FF3B5C"
ACCENT     = "#4B9FFF"

def draw_dashboard(rgb, gray, label, prob_fake, feats, hpf, Fmag, ela,
                   save_path="deepfake_result.png"):

    prob_real = 1 - prob_fake
    verdict_color = FAKE_COLOR if label == "FAKE" else REAL_COLOR

    plt.rcParams.update({
        "figure.facecolor": BG, "axes.facecolor": CARD,
        "axes.edgecolor": "#1E1E30", "axes.labelcolor": FG,
        "xtick.color": FG, "ytick.color": FG, "text.color": FG,
        "grid.color": "#1E1E30", "font.family": "monospace", "font.size": 8,
    })

    fig = plt.figure(figsize=(22, 16), facecolor=BG)

    # Title banner
    ax_title = fig.add_axes([0.0, 0.91, 1.0, 0.09])
    ax_title.set_facecolor(BG); ax_title.axis("off")
    ax_title.add_patch(FancyBboxPatch((0.01,0.05), 0.98, 0.88,
                       boxstyle="round,pad=0.01",
                       facecolor=verdict_color+"22",
                       edgecolor=verdict_color, linewidth=2,
                       transform=ax_title.transAxes))
    ax_title.text(0.5, 0.70,
                  f"{'⚠  DEEPFAKE DETECTED' if label=='FAKE' else '✔  AUTHENTIC IMAGE'}",
                  ha="center", va="center", fontsize=22, fontweight="bold",
                  color=verdict_color, transform=ax_title.transAxes)
    ax_title.text(0.5, 0.22,
                  f"Fake probability: {prob_fake*100:.1f}%   |   "
                  f"Real probability: {prob_real*100:.1f}%   |   "
                  f"Deepfake Source Attribution · Residual Frequency Analysis",
                  ha="center", va="center", fontsize=9, color=FG,
                  transform=ax_title.transAxes)

    gs = gridspec.GridSpec(3, 3, figure=fig,
                           hspace=0.45, wspace=0.35,
                           left=0.05, right=0.97,
                           top=0.89, bottom=0.04)

    # Panel 1: Original image
    ax1 = fig.add_subplot(gs[0, 0])
    ax1.imshow(rgb.astype(np.uint8))
    ax1.set_title("Input Image", fontsize=10, pad=6, color=FG)
    ax1.axis("off")
    # Coloured border
    for spine in ax1.spines.values():
        spine.set_edgecolor(verdict_color); spine.set_linewidth(3)

    # Panel 2: High-pass residual map
    ax2 = fig.add_subplot(gs[0, 1])
    hpf_disp = np.clip((hpf - hpf.min()) /
                       (np.ptp(hpf) + 1e-9) * 255, 0, 255)
    ax2.imshow(hpf_disp, cmap="inferno", vmin=0, vmax=255)
    ax2.set_title("High-Pass Residual", fontsize=10, pad=6, color=FG)
    ax2.axis("off")
    ax2.text(0.02, 0.96,
             f"μ={np.abs(hpf).mean():.3f}  σ={hpf.std():.3f}",
             transform=ax2.transAxes, fontsize=7, color=FG,
             va="top", bbox=dict(fc=CARD, ec="none", pad=2))

    # Panel 3: FFT magnitude heatmap
    ax3 = fig.add_subplot(gs[0, 2])
    log_F = np.log1p(np.abs(Fmag))
    ax3.imshow(log_F, cmap="plasma", origin="lower")
    ax3.set_title("FFT Magnitude (log)", fontsize=10, pad=6, color=FG)
    ax3.axis("off")

    # Panel 4: ELA heatmap
    ax4 = fig.add_subplot(gs[1, 0])
    ela_gray = ela.mean(axis=2)
    ela_norm = np.clip(ela_gray / (ela_gray.max()+1e-9), 0, 1)
    im4 = ax4.imshow(ela_norm, cmap="hot", vmin=0, vmax=1)
    ax4.set_title("ELA  (Error Level Analysis)", fontsize=10, pad=6, color=FG)
    ax4.axis("off")
    plt.colorbar(im4, ax=ax4, fraction=0.046, pad=0.02)
    ax4.text(0.02, 0.96,
             f"mean={ela_norm.mean():.3f}  max={ela_norm.max():.3f}",
             transform=ax4.transAxes, fontsize=7, color=FG,
             va="top", bbox=dict(fc=CARD, ec="none", pad=2))

    # Panel 5: DCT band energy
    ax5 = fig.add_subplot(gs[1, 1])
    dct_e   = np.log10(feats[32:40] + 1e-9)         # 8 DCT bands from feats
    bar_clr = plt.cm.cool(np.linspace(0.1, 0.9, 8))
    ax5.bar(range(8), dct_e, color=bar_clr, width=0.7)
    # Reference lines
    ax5.axhline(-1.5, ls="--", color=REAL_COLOR, lw=1.2, label="Real ref")
    ax5.axhline(-0.8, ls="--", color=FAKE_COLOR, lw=1.2, label="Fake ref")
    ax5.set_title("DCT Band Energy (log₁₀)", fontsize=10, pad=6, color=FG)
    ax5.set_xlabel("Band", fontsize=8); ax5.set_ylabel("log₁₀ Energy", fontsize=8)
    ax5.set_xticks(range(8)); ax5.set_xticklabels([f"B{i}" for i in range(8)])
    ax5.legend(fontsize=7, facecolor=CARD, edgecolor="#333")
    ax5.grid(axis="y", alpha=0.3)

    # Panel 6: Radial FFT spectrum vs references
    ax6 = fig.add_subplot(gs[1, 2])
    radial = feats[:32]
    freqs  = np.linspace(0, 0.5, 32)
    ax6.semilogy(freqs, radial, color=ACCENT, lw=2, label="This image")
    # Reference bands (calibrated from dataset)
    real_ref = 0.42 * np.exp(-freqs * 12)
    fake_ref = 0.55 * np.exp(-freqs * 8) + 0.04 * np.sin(freqs * 60)
    ax6.fill_between(freqs, real_ref*0.8, real_ref*1.2,
                     color=REAL_COLOR, alpha=0.20, label="Real band")
    ax6.fill_between(freqs, fake_ref*0.8, fake_ref*1.2,
                     color=FAKE_COLOR, alpha=0.20, label="Fake band")
    ax6.set_title("Radial FFT Spectrum vs References", fontsize=10, pad=6, color=FG)
    ax6.set_xlabel("Normalised Frequency", fontsize=8)
    ax6.set_ylabel("Magnitude (log)", fontsize=8)
    ax6.legend(fontsize=7, facecolor=CARD, edgecolor="#333")
    ax6.grid(True, alpha=0.25)

    # Panel 7: Confidence gauge:
    ax7 = fig.add_subplot(gs[2, 0])
    ax7.set_facecolor(CARD)
    ax7.set_xlim(0, 1); ax7.set_ylim(0, 1); ax7.axis("off")
    ax7.set_title("Detection Confidence", fontsize=10, pad=6, color=FG)

    # Background bar
    ax7.add_patch(FancyBboxPatch((0.05, 0.30), 0.90, 0.20,
                                 boxstyle="round,pad=0.01",
                                 fc="#1E1E30", ec="#333", lw=1))
    # Fill
    fill_w = 0.90 * prob_fake
    fill_c = FAKE_COLOR if prob_fake >= 0.5 else REAL_COLOR
    if fill_w > 0.01:
        ax7.add_patch(FancyBboxPatch((0.05, 0.30), fill_w, 0.20,
                                     boxstyle="round,pad=0.01",
                                     fc=fill_c+"CC", ec="none"))
    # Labels
    ax7.text(0.5,  0.65, f"{prob_fake*100:.1f}%  FAKE",
             ha="center", va="center", fontsize=16, fontweight="bold",
             color=FAKE_COLOR)
    ax7.text(0.5, 0.15, f"{prob_real*100:.1f}%  REAL",
             ha="center", va="center", fontsize=16, fontweight="bold",
             color=REAL_COLOR)
    ax7.text(0.5, 0.85, label,
             ha="center", va="center", fontsize=28, fontweight="bold",
             color=verdict_color)

    # Panel 8: Feature radar (azimuthal + scalar):
    ax8 = fig.add_subplot(gs[2, 1], projection="polar")
    azim_vals = feats[40:52]   # 12 azimuthal
    azim_norm = (azim_vals - azim_vals.min()) / (np.ptp(azim_vals)+1e-9)
    theta = np.linspace(0, 2*np.pi, 12, endpoint=False)
    theta = np.concatenate([theta, [theta[0]]])
    vals  = np.concatenate([azim_norm, [azim_norm[0]]])
    ax8.plot(theta, vals, color=verdict_color, lw=2)
    ax8.fill(theta, vals, color=verdict_color, alpha=0.25)
    ax8.set_facecolor(CARD)
    ax8.set_title("Azimuthal Anisotropy\n(FFT directional bias)",
                  fontsize=9, pad=14, color=FG)
    ax8.tick_params(colors=FG)

    # Panel 9: Scalar feature summary table:
    ax9 = fig.add_subplot(gs[2, 2])
    ax9.axis("off")
    ax9.set_title("Feature Summary", fontsize=10, pad=6, color=FG)

    scalar_labels = ["FFT mean", "FFT std", "HPF mean", "HPF std",
                     "JPEG ghost", "JPEG ghost σ", "ELA mean", "ELA std",
                     "Chroma residual"]
    scalar_vals   = feats[52:61]

    # Typical real vs fake reference values
    real_refs = [0.41, 0.18, 0.02, 0.08, 0.12, 0.04, 0.05, 0.03, 0.04]
    fake_refs = [0.50, 0.23, 0.08, 0.15, 0.35, 0.10, 0.18, 0.10, 0.16]

    rows = []
    for name, val, rr, fr in zip(scalar_labels, scalar_vals, real_refs, fake_refs):
        closer = "REAL" if abs(val-rr) <= abs(val-fr) else "FAKE"
        rows.append([name, f"{val:.4f}", f"{rr:.3f}", f"{fr:.3f}", closer])

    tbl = ax9.table(
        cellText=rows,
        colLabels=["Feature","Value","Real ref","Fake ref","Signal"],
        cellLoc="center", loc="center", bbox=[0,0,1,1]
    )
    tbl.auto_set_font_size(False); tbl.set_fontsize(7.5)
    for (row, col), cell in tbl.get_celld().items():
        if row == 0:
            cell.set_facecolor("#1A1A35")
            cell.set_text_props(color="#AACCFF", fontweight="bold")
        else:
            verdict_cell = rows[row-1][4]
            if col == 4:
                cell.set_facecolor(FAKE_COLOR+"33" if verdict_cell=="FAKE"
                                   else REAL_COLOR+"33")
                cell.set_text_props(color=FAKE_COLOR if verdict_cell=="FAKE"
                                    else REAL_COLOR, fontweight="bold")
            else:
                cell.set_facecolor(CARD if row%2 else "#15152A")
                cell.set_text_props(color=FG)
        cell.set_edgecolor("#1E1E30")

    fig.savefig(save_path, dpi=150, bbox_inches="tight", facecolor=BG)
    print(f"\n✔  Dashboard saved → {save_path}")
    return fig


# 5. Main entry-point:

def run_detector(image_source):
    if isinstance(image_source, np.ndarray):
        rgb  = image_source.astype(np.float32)
        gray = np.mean(rgb, axis=2).astype(np.float32)
    else:
        rgb, gray = load_image(image_source)

    print(f"▶  Image loaded  — shape {rgb.shape}")
    print("▶  Extracting frequency features …")
    label, prob_fake, feats, hpf, Fmag, ela = predict(rgb, gray)
    print(f"▶  Verdict : {label}  ({prob_fake*100:.1f}% fake confidence)")
    fig = draw_dashboard(rgb, gray, label, prob_fake, feats, hpf, Fmag, ela)
    return label, prob_fake, fig


def colab_upload_and_detect():
    """Run this function in Google Colab for an interactive file upload."""
    try:
        from google.colab import files
        from IPython.display import display, Image as IPImage
        import matplotlib
        matplotlib.use("Agg")
        # keep Agg for saving; display via IPImage

        print("=" * 60)
        print("  DEEPFAKE IMAGE DETECTOR")
        print("  Upload a face image (jpg / png / webp)")
        print("=" * 60)

        uploaded = files.upload()
        if not uploaded:
            print("✖  No file uploaded.")
            return

        fname = list(uploaded.keys())[0]
        data  = uploaded[fname]
        print(f"\n✔  Received: {fname}  ({len(data)/1024:.1f} KB)")

        label, prob_fake, fig = run_detector(data)
        save_path = "deepfake_result.png"
        fig.savefig(save_path, dpi=150, bbox_inches="tight", facecolor=BG)
        plt.close(fig)

        print("\n── FINAL VERDICT ──────────────────────────────────────")
        print(f"   Image    : {fname}")
        print(f"   Decision : {'⚠  DEEPFAKE' if label=='FAKE' else '✔  REAL'}")
        print(f"   Fake %   : {prob_fake*100:.1f}%")
        print(f"   Real %   : {(1-prob_fake)*100:.1f}%")
        print("───────────────────────────────────────────────────────")

        display(IPImage(save_path))
        files.download(save_path)

    except ImportError:
        # Not in Colab — fall back to local demo with a synthetic image
        print("▶  Not in Colab. Running demo with a synthetic test image …")
        demo_image = np.random.randint(80, 200, (256, 256, 3), dtype=np.uint8)
        # inject a fake-like checkerboard artefact
        for i in range(0, 256, 32):
            for j in range(0, 256, 32):
                if (i//32 + j//32) % 2 == 0:
                    demo_image[i:i+32, j:j+32] = np.clip(
                        demo_image[i:i+32, j:j+32].astype(int) + 40, 0, 255)
        label, prob_fake, fig = run_detector(demo_image)
        out = "deepfake_result_demo.png"
        fig.savefig(out, dpi=150, bbox_inches="tight", facecolor=BG)
        plt.close(fig)
        print(f"   Demo result saved → {out}")



if __name__ == "__main__":
    colab_upload_and_detect()